#ifndef BUBBLE_ESP32_BOARD_CONFIG_H
#define BUBBLE_ESP32_BOARD_CONFIG_H

#include "driver/spi_common.h"
#include "hal/adc_types.h"
#include "hal/i2c_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BUBBLE_ESP32_BOARD_MODEL "bubble-cloud-esp32-reference"

#define BUBBLE_ESP32_BOARD_AUDIO_SAMPLE_RATE_HZ 44100
#define BUBBLE_ESP32_BOARD_AUDIO_BLOCK_FRAMES 32

#define BUBBLE_ESP32_BOARD_ENCODER_COUNT 3
#define BUBBLE_ESP32_BOARD_ENCODER_0_GPIO_A 32
#define BUBBLE_ESP32_BOARD_ENCODER_0_GPIO_B 34
#define BUBBLE_ESP32_BOARD_ENCODER_0_GPIO_CLICK 35
#define BUBBLE_ESP32_BOARD_ENCODER_1_GPIO_A 3
#define BUBBLE_ESP32_BOARD_ENCODER_1_GPIO_B 39
#define BUBBLE_ESP32_BOARD_ENCODER_1_GPIO_CLICK 4
#define BUBBLE_ESP32_BOARD_ENCODER_2_GPIO_A 16
#define BUBBLE_ESP32_BOARD_ENCODER_2_GPIO_B 17
#define BUBBLE_ESP32_BOARD_ENCODER_2_GPIO_CLICK 19

#define BUBBLE_ESP32_BOARD_FOOTSWITCH_BYPASS_GPIO 5
#define BUBBLE_ESP32_BOARD_FOOTSWITCH_ACTION_GPIO 12

#define BUBBLE_ESP32_BOARD_EXPRESSION_ADC_UNIT ADC_UNIT_1
#define BUBBLE_ESP32_BOARD_EXPRESSION_ADC_CHANNEL ADC_CHANNEL_0

#define BUBBLE_ESP32_BOARD_TFT_SPI_HOST SPI2_HOST
#define BUBBLE_ESP32_BOARD_TFT_SPI_CLOCK_HZ 40000000
#define BUBBLE_ESP32_BOARD_TFT_SPI_SCLK_GPIO 14
#define BUBBLE_ESP32_BOARD_TFT_SPI_MOSI_GPIO 13
#define BUBBLE_ESP32_BOARD_TFT_SPI_MISO_GPIO -1
#define BUBBLE_ESP32_BOARD_TFT_SPI_CS_GPIO 15
#define BUBBLE_ESP32_BOARD_TFT_DC_GPIO 2
#define BUBBLE_ESP32_BOARD_TFT_RESET_GPIO 18
#define BUBBLE_ESP32_BOARD_TFT_BACKLIGHT_GPIO 23

#define BUBBLE_ESP32_BOARD_CODEC_I2S_BCLK_GPIO 26
#define BUBBLE_ESP32_BOARD_CODEC_I2S_WS_GPIO 25
#define BUBBLE_ESP32_BOARD_CODEC_I2S_DIN_GPIO 33
#define BUBBLE_ESP32_BOARD_CODEC_I2S_DOUT_GPIO 22
#define BUBBLE_ESP32_BOARD_CODEC_I2S_MCLK_GPIO 0

#define BUBBLE_ESP32_BOARD_CODEC_CONTROL_I2C_PORT I2C_NUM_0
#define BUBBLE_ESP32_BOARD_CODEC_CONTROL_I2C_SDA_GPIO 21
#define BUBBLE_ESP32_BOARD_CODEC_CONTROL_I2C_SCL_GPIO 27
#define BUBBLE_ESP32_BOARD_CODEC_CONTROL_I2C_HZ 400000
#define BUBBLE_ESP32_BOARD_CODEC_CONTROL_I2C_ADDRESS 0x18

#ifdef __cplusplus
}
#endif

#endif // BUBBLE_ESP32_BOARD_CONFIG_H
