#!/usr/bin/env python3
"""Generate the browser macro matrix bundle from docs/macro_matrix.yaml.

The source file intentionally keeps the historical .yaml extension, but its
contents are JSON-compatible so it can be parsed without third-party deps.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate macro_matrix.js for the web UI")
    parser.add_argument("--source", default="docs/macro_matrix.yaml", help="JSON-compatible matrix source")
    parser.add_argument("--output", default="web/frontend/macro_matrix.js", help="Generated JS output")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source = Path(args.source)
    output = Path(args.output)
    matrix = json.loads(source.read_text(encoding="utf-8"))
    payload = json.dumps(matrix, ensure_ascii=False, indent=2)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by scripts/generate_macro_matrix_js.py from docs/macro_matrix.yaml.\n"
        "// Do not edit by hand; update the source document and regenerate.\n"
        "(function initMacroMatrix(global) {\n"
        "  global.BubbleCloudMacroMatrix = Object.freeze(\n"
        f"{payload}\n"
        "  );\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : window);\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
